name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make

    - name: Build
      env: 
        ACR_USER: ${{ secrets.ACR_USER }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      run: ./image-syncer --auth=auth.json --images=images.json --days=5 --proc=1
