name: Sync docker images of minikube to Alibaba Cloud

on:
  workflow_dispatch:
  schedule:
    # every day at 7am & 7pm pacific
    - cron: "0 2,14 * * *"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: denverdino/image-syncer
        path: ./image-syncer

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: cd image-syncer && make

    - name: Synchronize images to Alibaba Cloud Container Registry Service
      env: 
        ACR_USER: ${{ secrets.ACR_USER }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      run: cd image-syncer && ./image-syncer --auth=auth.json --images=images.json --days=2 --proc=2
